package com.mbg.test.dao;

import com.mbg.test.model.ConfigParam;
import com.mbg.test.model.ConfigParamExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int countByExample(ConfigParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int insert(ConfigParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int insertSelective(ConfigParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    List<ConfigParam> selectByExample(ConfigParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    ConfigParam selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfigParam record, @Param("example") ConfigParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfigParam record, @Param("example") ConfigParamExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_config_param
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigParam record);
}