package com.mbg.test.dao;

import com.mbg.test.model.EhPoint;
import com.mbg.test.model.EhPointExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EhPointMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int countByExample(EhPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int deleteByExample(EhPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int insert(EhPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int insertSelective(EhPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    List<EhPoint> selectByExample(EhPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    EhPoint selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") EhPoint record, @Param("example") EhPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int updateByExample(@Param("record") EhPoint record, @Param("example") EhPointExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int updateByPrimaryKeySelective(EhPoint record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_point
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    int updateByPrimaryKey(EhPoint record);
}