package com.mbg.test.dao;

import com.mbg.test.model.LogonInfo;
import com.mbg.test.model.LogonInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogonInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int countByExample(LogonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int deleteByExample(LogonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int insert(LogonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int insertSelective(LogonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    List<LogonInfo> selectByExample(LogonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    LogonInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") LogonInfo record, @Param("example") LogonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") LogonInfo record, @Param("example") LogonInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(LogonInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eh_logon_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(LogonInfo record);
}