package com.mbg.test.model;

import java.util.Date;

public class EhPoint {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.point_type
     *
     * @mbggenerated
     */
    private String pointType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.point_amount
     *
     * @mbggenerated
     */
    private Long pointAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.gmt_create
     *
     * @mbggenerated
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_point.gmt_modify
     *
     * @mbggenerated
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.id
     *
     * @return the value of eh_point.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.id
     *
     * @param id the value for eh_point.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.uid
     *
     * @return the value of eh_point.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.uid
     *
     * @param uid the value for eh_point.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.point_type
     *
     * @return the value of eh_point.point_type
     *
     * @mbggenerated
     */
    public String getPointType() {
        return pointType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.point_type
     *
     * @param pointType the value for eh_point.point_type
     *
     * @mbggenerated
     */
    public void setPointType(String pointType) {
        this.pointType = pointType == null ? null : pointType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.point_amount
     *
     * @return the value of eh_point.point_amount
     *
     * @mbggenerated
     */
    public Long getPointAmount() {
        return pointAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.point_amount
     *
     * @param pointAmount the value for eh_point.point_amount
     *
     * @mbggenerated
     */
    public void setPointAmount(Long pointAmount) {
        this.pointAmount = pointAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.status
     *
     * @return the value of eh_point.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.status
     *
     * @param status the value for eh_point.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.gmt_create
     *
     * @return the value of eh_point.gmt_create
     *
     * @mbggenerated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.gmt_create
     *
     * @param gmtCreate the value for eh_point.gmt_create
     *
     * @mbggenerated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_point.gmt_modify
     *
     * @return the value of eh_point.gmt_modify
     *
     * @mbggenerated
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_point.gmt_modify
     *
     * @param gmtModify the value for eh_point.gmt_modify
     *
     * @mbggenerated
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}