package com.mbg.test.model;

import java.util.Date;

public class LogonInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.uid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.logon_type
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String logonType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.logon_name
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String logonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.verify_code
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String verifyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.status
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.status_uuid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String statusUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.memo
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.gmt_create
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.gmt_modify
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.gmt_verify_exp
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtVerifyExp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_logon_info.gmt_verify_pas
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtVerifyPas;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.id
     *
     * @return the value of eh_logon_info.id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.id
     *
     * @param id the value for eh_logon_info.id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.uid
     *
     * @return the value of eh_logon_info.uid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.uid
     *
     * @param uid the value for eh_logon_info.uid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.logon_type
     *
     * @return the value of eh_logon_info.logon_type
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getLogonType() {
        return logonType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.logon_type
     *
     * @param logonType the value for eh_logon_info.logon_type
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setLogonType(String logonType) {
        this.logonType = logonType == null ? null : logonType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.logon_name
     *
     * @return the value of eh_logon_info.logon_name
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getLogonName() {
        return logonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.logon_name
     *
     * @param logonName the value for eh_logon_info.logon_name
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setLogonName(String logonName) {
        this.logonName = logonName == null ? null : logonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.verify_code
     *
     * @return the value of eh_logon_info.verify_code
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getVerifyCode() {
        return verifyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.verify_code
     *
     * @param verifyCode the value for eh_logon_info.verify_code
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setVerifyCode(String verifyCode) {
        this.verifyCode = verifyCode == null ? null : verifyCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.status
     *
     * @return the value of eh_logon_info.status
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.status
     *
     * @param status the value for eh_logon_info.status
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.status_uuid
     *
     * @return the value of eh_logon_info.status_uuid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getStatusUuid() {
        return statusUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.status_uuid
     *
     * @param statusUuid the value for eh_logon_info.status_uuid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setStatusUuid(String statusUuid) {
        this.statusUuid = statusUuid == null ? null : statusUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.memo
     *
     * @return the value of eh_logon_info.memo
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.memo
     *
     * @param memo the value for eh_logon_info.memo
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.gmt_create
     *
     * @return the value of eh_logon_info.gmt_create
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.gmt_create
     *
     * @param gmtCreate the value for eh_logon_info.gmt_create
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.gmt_modify
     *
     * @return the value of eh_logon_info.gmt_modify
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.gmt_modify
     *
     * @param gmtModify the value for eh_logon_info.gmt_modify
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.gmt_verify_exp
     *
     * @return the value of eh_logon_info.gmt_verify_exp
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtVerifyExp() {
        return gmtVerifyExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.gmt_verify_exp
     *
     * @param gmtVerifyExp the value for eh_logon_info.gmt_verify_exp
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtVerifyExp(Date gmtVerifyExp) {
        this.gmtVerifyExp = gmtVerifyExp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_logon_info.gmt_verify_pas
     *
     * @return the value of eh_logon_info.gmt_verify_pas
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtVerifyPas() {
        return gmtVerifyPas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_logon_info.gmt_verify_pas
     *
     * @param gmtVerifyPas the value for eh_logon_info.gmt_verify_pas
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtVerifyPas(Date gmtVerifyPas) {
        this.gmtVerifyPas = gmtVerifyPas;
    }
}