package com.mbg.test.model;

import java.util.Date;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.uid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.id_no
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.user_nick
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String userNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.user_name
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.pwd_digest
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String pwdDigest;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.pwd_salt
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String pwdSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.sex
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.email
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.phone
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.status
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.user_type
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String userType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.reg_src_id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String regSrcId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.user_loc
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private String userLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.gmt_birth
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtBirth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.gmt_create
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eh_user_info.gmt_modify
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    private Date gmtModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.id
     *
     * @return the value of eh_user_info.id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.id
     *
     * @param id the value for eh_user_info.id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.uid
     *
     * @return the value of eh_user_info.uid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.uid
     *
     * @param uid the value for eh_user_info.uid
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.id_no
     *
     * @return the value of eh_user_info.id_no
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.id_no
     *
     * @param idNo the value for eh_user_info.id_no
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.user_nick
     *
     * @return the value of eh_user_info.user_nick
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getUserNick() {
        return userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.user_nick
     *
     * @param userNick the value for eh_user_info.user_nick
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setUserNick(String userNick) {
        this.userNick = userNick == null ? null : userNick.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.user_name
     *
     * @return the value of eh_user_info.user_name
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.user_name
     *
     * @param userName the value for eh_user_info.user_name
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.pwd_digest
     *
     * @return the value of eh_user_info.pwd_digest
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getPwdDigest() {
        return pwdDigest;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.pwd_digest
     *
     * @param pwdDigest the value for eh_user_info.pwd_digest
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setPwdDigest(String pwdDigest) {
        this.pwdDigest = pwdDigest == null ? null : pwdDigest.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.pwd_salt
     *
     * @return the value of eh_user_info.pwd_salt
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getPwdSalt() {
        return pwdSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.pwd_salt
     *
     * @param pwdSalt the value for eh_user_info.pwd_salt
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setPwdSalt(String pwdSalt) {
        this.pwdSalt = pwdSalt == null ? null : pwdSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.sex
     *
     * @return the value of eh_user_info.sex
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.sex
     *
     * @param sex the value for eh_user_info.sex
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.email
     *
     * @return the value of eh_user_info.email
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.email
     *
     * @param email the value for eh_user_info.email
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.phone
     *
     * @return the value of eh_user_info.phone
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.phone
     *
     * @param phone the value for eh_user_info.phone
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.status
     *
     * @return the value of eh_user_info.status
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.status
     *
     * @param status the value for eh_user_info.status
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.user_type
     *
     * @return the value of eh_user_info.user_type
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.user_type
     *
     * @param userType the value for eh_user_info.user_type
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.reg_src_id
     *
     * @return the value of eh_user_info.reg_src_id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getRegSrcId() {
        return regSrcId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.reg_src_id
     *
     * @param regSrcId the value for eh_user_info.reg_src_id
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setRegSrcId(String regSrcId) {
        this.regSrcId = regSrcId == null ? null : regSrcId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.user_loc
     *
     * @return the value of eh_user_info.user_loc
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public String getUserLoc() {
        return userLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.user_loc
     *
     * @param userLoc the value for eh_user_info.user_loc
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setUserLoc(String userLoc) {
        this.userLoc = userLoc == null ? null : userLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.gmt_birth
     *
     * @return the value of eh_user_info.gmt_birth
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtBirth() {
        return gmtBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.gmt_birth
     *
     * @param gmtBirth the value for eh_user_info.gmt_birth
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtBirth(Date gmtBirth) {
        this.gmtBirth = gmtBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.gmt_create
     *
     * @return the value of eh_user_info.gmt_create
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.gmt_create
     *
     * @param gmtCreate the value for eh_user_info.gmt_create
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eh_user_info.gmt_modify
     *
     * @return the value of eh_user_info.gmt_modify
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public Date getGmtModify() {
        return gmtModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eh_user_info.gmt_modify
     *
     * @param gmtModify the value for eh_user_info.gmt_modify
     *
     * @mbggenerated Thu Mar 17 10:52:23 CST 2016
     */
    public void setGmtModify(Date gmtModify) {
        this.gmtModify = gmtModify;
    }
}